config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :undertakes
      get :searches
    end
  end

  get 'corporation', to: 'users#corporationes'
  get 'apply', to: 'users#applies'
  get 'applier', to: 'companies#appliers'
  get 'clogin', to: 'sessions#c_new'
  post 'clogin', to: 'sessions#c_create'
  delete 'clogout', to: 'sessions#c_destroy'
  get 'confirm', to: 'jobs#confirm'
  
  get 'csignup', to: 'companies#new'
  resources :companies, only: [:index, :show, :new, :create, :update]
  resources :relationships, only: [:create, :destroy, :update, :done]
  resources :jobs, only: [:new, :show, :create, :destroy, :update]
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @companies = Company.all
      @jobs = Job.all#.page(params[:page]).per(5)  #トップページのjobs情報取得
    end
    if clogged_in?
      @job = current_company.jobs.build
      @jobs = current_company.jobs.order(id: :desc).page(params[:page])
    end
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h1 class="card-title"><%= current_user.name %></h1>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(current_user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= root_url %>" class="nav-link <%= 'active' %>">お仕事一覧<span class="badge badge-primary"></span></a></li>
      <li class="nav-item"><a href="<%= apply_path(@user) %>" class="nav-link">受けたお仕事<span class="badge badge-secondary"></span></a></li>
      <li class="nav-item"><a href="<%= corporation_path %>" class="nav-link">企業一覧<span class="badge badge-secondary"></span></a></li>
      <li class="nav-item"><a href="<%= searches_user_path(@user) %>" class="nav-link">お仕事検索<span class="badge badge-primary"></span></a></li>
    </ul>
    <%= render 'users/jobs',jobs: @jobs %>
  </div>
</div>
<% elsif clogged_in? %>
    <div class="row">
    <aside class="col-sm-4">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"><%= current_company.name %></h3>
        </div>
        <div class="card-body">
          <img class="rounded img-fluid" src="<%= gravatar_url(current_company, { size: 500 }) %>" alt="">
        </div>
        <div class="card-body">
          <%= link_to '新規お仕事の登録',new_job_path, class: "btn btn-primary" %>
        </div>
      </div>
    </aside>
    <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= root_url %>" class="nav-link <%= 'active' %>">お仕事一覧<span class="badge badge-secondary"></span></a></li>
      <li class="nav-item"><a href="<%= applier_path %>">受託者一覧<span class="badge badge-secondary"></span></a></li>
    </ul>
    <%= render 'jobs/jobs', jobs: @jobs %>
  </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1 class="text-uppercase text-muted font-weight-bold">お仕事マッチングサイト</h1>
    </div> 
  </div>
  <div class="container py-4">
    <div class="text-center">
      <%= link_to 'お仕事をご登録の企業様', new_company_path %>
    </div>
  </div>
  <div class="container py-4">
    <div class="text-center">
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>