config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :undertakes
      get :searches
    end
  end

  get 'corporation', to: 'users#corporationes'
  get 'apply', to: 'users#applies'
  get 'applier', to: 'companies#appliers'
  get 'clogin', to: 'sessions#c_new'
  post 'clogin', to: 'sessions#c_create'
  delete 'clogout', to: 'sessions#c_destroy'
  get 'confirm', to: 'jobs#confirm'
  
  get 'csignup', to: 'companies#new'
  resources :companies, only: [:index, :show, :new, :create, :update]
  resources :relationships, only: [:create, :destroy, :update, :done]
  resources :jobs, only: [:new, :show, :create, :destroy, :update]
  
end

app/models/company.rb
class Company < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :jobs

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    if logged_in?
     redirect_to root_url
    elsif clogged_in?
     redirect_to root_url
    else
     redirect_to clogin_url
    end
  end

  def show
    if clogged_in?
      @company = current_company
      @jobs = @company.jobs.order(id: :desc).page(params[:page])
    elsif logged_in?
      if Company.find_by(id: params[:id]) == nil
        redirect_to root_url
      else
        @company = Company.find(params[:id])
        @jobs = @company.jobs.order(id: :desc).page(params[:page])
      end
    else
      redirect_to clogin_url
    end
  end

  def new
    require_new
  end
  
  def create
    @company = Company.new(company_params)

    if @company.save
      flash[:success] = '企業様を登録しました。'
      redirect_to @company
    else
      flash.now[:danger] = '企業様の登録に失敗しました。'
      render :new
    end
  end
  
  def appliers
    @company = current_company
    array = Array.new
    @members  = Array.new
    jobs = @company.jobs.order(id: :desc)
    jobs.each do |job|
      unless Relationship.find_by(job_id: job.id)==nil then
        a =  Relationship.where(job_id: job.id).pluck(:id).size
        if a > 1 then
          ary = Relationship.where(job_id: job.id).pluck(:id)
          ary.each do |youso|
            array.push(youso)
          end
        elsif
          array.push(Relationship.where(job_id: job.id).pluck(:id))
        end
      end
    end
  end
  
  private

  def company_params
    params.require(:company).permit(:name, :email, :password, :password_confirmation)
  end
  
  def require_new
    if logged_in?
      redirect_to root_url
    elsif clogged_in?
      redirect_to root_url
    else
      @company = Company.new
    end
  end
  
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def gravatar_url(company, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(company.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/companies/_appliers.html.erb
<% jobs = current_company.jobs %>
<% jobs.each do |job| %>
  <% unless Relationship.find_by(job_id: job.id)==nil then %>
    <% relationshiip = Relationship.find_by(job_id: job.id) %>
    <div>
      <%= relationshiip.job.status %>
    </div>
    <div>
      <h5 class="mt-0">受託者名：<%= link_to relationshiip.user.name,user_path(relationshiip.user) %></h5>
    </div>
    <div>
      <h6 class="mt-0">委託お仕事：<%= link_to relationshiip.job.content,job_path(relationshiip.job) %></h6><br>
    </div>
  <% end %>
<% end %>

app/views/companies/_companies.html.erb
<% if @companies.any? %>
  <% @companies.each do |company| %>
  <li class="media  mb-3">
    <img class="mr-2 rounded" src="<%= gravatar_url(company, { size: 50 }) %>" alt="">
    <div class="media-body">
        <div>
          <b><%= link_to company.name,company %></b>
        </div>
        <div>
         <span class="text-muted"> registered at <%= company.created_at.to_s(:datetime_jp) %></span>
        </div>
    </div>
  </li>
  <% end %>
<% end %>

app/views/companies/_jobs.html.erb
<ul class="list-unstyled">
  <% jobs.each do |job| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(job.company, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <b><%= link_to job.content,job %></b><span class="text-muted"> registered at <%= job.created_at.to_s(:datetime_jp) %></span>
        </div>
        <div>
          <% if current_company == job.company %>
            <% unless Relationship.find_by(job_id: job.id)==nil then %>
              <% if job.status == '確認中'%>
                <span class="text-muted"><%= job.status %></span>
                <%= form_with(model: job, local: true) do |f| %>
                  <%= hidden_field_tag :job_id, job.id %>
                  <%= f.submit '委託確定', class: 'btn btn-primary btn-sm' %>
                <% end %>
                <%#= form_with(model: current_user.relationships.find_by(job_id: job.id), local: true, method: :delete) do |f| %>
                  <%#= hidden_field_tag :job_id, job.id %>
                  <%#= f.submit 'キャンセル', class: 'btn btn-danger btn-sm' %>
                <%# end %>
              <% else %>
                <span class="text-muted">委託確定</span>
              <% end %>
            <% else %>
              <%= link_to "取下げ", job, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate jobs %>
</ul>

app/views/companies/appliers.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @company.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@company, { size: 500 }) %>" alt="">
      </div>
      <div class="card-body">
        <%= link_to '新規お仕事の登録',new_job_path, class: "btn btn-primary" %>
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= root_url %>" class="nav-link">お仕事一覧<span class="badge badge-secondary"></span></a></li>
      <li class="nav-item"><a href="<%= applier_path %>" class="nav-link <%= 'active' %>">受託者一覧<span class="badge badge-primary"></span></a></li>
    </ul>
    <%= render 'appliers'%>
  </div>
</div>

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/deletecreate.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/deleteindex.html.erb
<h1>Companies#index</h1>
<p>Find me in app/views/companies/index.html.erb</p>
<%= render 'companies', companies: @companies %>

app/views/companies/index.html.erb
<h1>Companies#index</h1>
<p>Find me in app/views/companies/index.html.erb</p>
<%= render 'companies', companies: @companies %>

app/views/companies/new.html.erb
<div class="text-center">
  <h1>企業様会員登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @company, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, '御社名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/companies/show.html.erb
<h1>企業様の詳細</h1>
<div class="media">
  <img class="mr-2" src="/assets/company.png">
  <div class="media-body">
    <h3 class="mt-0">企業様名：<%= @company.name %></h3>
    <h5 class="mt-0">email：<%= @company.email %></h5>
    <button><%= link_to '戻る', root_path %></button>
  </div>
</div>