config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :undertakes
      get :searches
    end
  end

  get 'corporation', to: 'users#corporationes'
  get 'apply', to: 'users#applies'
  get 'applier', to: 'companies#appliers'
  get 'clogin', to: 'sessions#c_new'
  post 'clogin', to: 'sessions#c_create'
  delete 'clogout', to: 'sessions#c_destroy'
  get 'confirm', to: 'jobs#confirm'
  
  get 'csignup', to: 'companies#new'
  resources :companies, only: [:index, :show, :new, :create, :update]
  resources :relationships, only: [:create, :destroy, :update, :done]
  resources :jobs, only: [:new, :show, :create, :destroy, :update]
  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_myerror_messages.html.erb
<% flash.each do |message_type, message| %>
<div id="error_explanation" class="alert alert-warning">
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <% if logged_in? %>
      <a class="navbar-brand text-primary font-weight-bold" href="/">Jobs</a>
    <% elsif clogged_in? %>
      <a class="navbar-brand text-primary font-weight-bold" href="/">Jobs</a>
    <% else %>
      <a class="navbar-brand" href="/">Jobs</a>
    <% end %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% elsif clogged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_company.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', company_path(current_company) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', clogout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Signup</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown-item"><%= link_to 'ユーザーSignup', signup_path %></li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to '企業様Signup', csignup_path %></li>
              </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Login</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown-item"><%= link_to 'ユーザーLogin', login_path %></li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to '企業様Login', clogin_path %></li>
              </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Jobs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>